[workspace]
authors = ["Georgeos Hardo <gh464@cantab.ac.uk>"]
channels = ["conda-forge"]
name = "PyMMM"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11"
nd2 = "*"
xarray = ">=2026.2.0,<2027"
dask = "*"
distributed = "*"
zarr = "*"
numcodecs = ">=0.16.5,<0.17"
numpy = "*"
scipy = "*"
pystackreg = "*"
scikit-image = "*"
matplotlib = "*"
tqdm = "*"
pandas = "*"
hvplot = "*"
panel = "*"
bokeh = "*"
jupyterlab = "*"
ipykernel = "*"
ipywidgets = "*"
datashader = "*"
jupyter_bokeh = "*"
cmake = "*"
pytest = "*"

[tasks]
test = "python -m pytest tests/ -v"
notebook = "python -m jupyter lab"

[activation.env]
PYTHONPATH = "$PIXI_PROJECT_ROOT"

[pypi-dependencies]
omnipose = ">=1.1.4, <2"
opencv-python-headless = ">=4.13"
ndv = { version = ">=0.5, <0.6", extras = ["jup"] }
